name: UserManagement
extensions:
- name: dapr
services:
- name: registeruser
  project: RegisterUser/RegisterUser.csproj
  bindings:
  - protocol: https
    port: 7250
- name: searchusers
  project: SearchUsers/SearchUsers.csproj
  bindings:
  - protocol: https
    port: 7001
- name: redis
  image: redis
  bindings:
    - port: 6379